/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as MapRouteImport } from './routes/map'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as AlertsIdRouteImport } from './routes/alerts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIdRoute = AlertsIdRouteImport.update({
  id: '/alerts/$id',
  path: '/alerts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/': typeof AlertsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts': typeof AlertsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/alerts/$id': typeof AlertsIdRoute
  '/alerts/': typeof AlertsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forecast'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/alerts/$id'
    | '/alerts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forecast'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/alerts/$id'
    | '/alerts'
  id:
    | '__root__'
    | '/'
    | '/forecast'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/alerts/$id'
    | '/alerts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastRoute: typeof ForecastRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  AlertsIdRoute: typeof AlertsIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/$id': {
      id: '/alerts/$id'
      path: '/alerts/$id'
      fullPath: '/alerts/$id'
      preLoaderRoute: typeof AlertsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastRoute: ForecastRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  AlertsIdRoute: AlertsIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
